# Generated by Django 2.2.6 on 2019-10-30 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True, verbose_name='email address')),
                ('active', models.BooleanField(default=True)),
                ('usertype', models.CharField(choices=[('A', 'Admin'), ('D', 'Device'), ('S', 'Staff')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
